name: "Build & Push images"

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/main.yml'
      - '.github/workflows/build.yml'
      - 'Dockerfile'
    branches:
      - master
  schedule:
    # https://crontab.guru/#0_0_*_*_0
    # At 00:00 on Sunday.
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: shiroko/ubuntu:latest
          platforms: 'linux/amd64,linux/arm/v7,linux/arm64/v8'
